blank_issues_enabled: false
contact_links:
  - name: Ask a question on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/blogdown
    about: Please ask and answer questions here.
  - name: Ask a question on RStudio Community
    url: https://community.rstudio.com/tag/blogdown
    about: Please ask and answer questions here.
